# Generated by Django 4.1.6 on 2023-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('flavour', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('shape', models.CharField(max_length=230)),
                ('weight', models.CharField(max_length=250)),
                ('layer', models.CharField(max_length=200)),
            ],
        ),
    ]
